### ISSUE TITLE
(EasyForm) Combobox regression

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx_widgets#10]
**actual result:**
![image](https://user-images.githubusercontent.com/17744188/88048261-af326780-cb5b-11ea-9376-1392cbf35186.png)

1. Combobox element lost style that it have before
2. Setting value by code doesn't work 

**expected result:**
![image](https://user-images.githubusercontent.com/17744188/88048770-9aa29f00-cb5c-11ea-9d5d-dc387e29bbdd.png)

**Comment by EfimovVladimir** [comment]
(Jupyter Notebook; Ubuntu; Groovy kernel) **not fixed** :
![image](https://user-images.githubusercontent.com/17744188/91028124-ad017400-e605-11ea-9558-efa3e3a3031a.png)
(Jupyter Notebook; Ubuntu; Python kernel) **not fixed** :
![image](https://user-images.githubusercontent.com/17744188/91028330-01a4ef00-e606-11ea-8db0-b6a5716fb36e.png)
(Jupyter Lab; Ubuntu; Groovy kernel) style is fine, but  **setting value not fixed** :
![image](https://user-images.githubusercontent.com/17744188/91028995-e4245500-e606-11ea-870f-759bee6a1d2a.png)
(Jupyter Lab; Ubuntu; Python kernel) style is fine, but  **setting value not fixed** :
![image](https://user-images.githubusercontent.com/17744188/91028712-87c13580-e606-11ea-8417-cb60097aa768.png)

**Comment by jaroslawmalekcodete** [comment]
@EfimovVladimir 
please test "fix easy form combobox"

**Comment by EfimovVladimir** [comment]
the setting value is OK
the style on Notebook not fixed
