### ISSUE TITLE
(Plot) Time value of SimpleTimePlot is wrong

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx_widgets#11]
**code to reproduce:**
```
from beakerx_widgets.plots import *
import pandas as pd
tableRows = pd.read_csv('../../../doc/resources/data/interest-rates.csv')
SimpleTimePlot(tableRows, ["y1", "y10"], 
                   timeColumn="time", 
                   displayNames=["1 Year", "10 Year"])
```
**actual result:**
![image](https://user-images.githubusercontent.com/17744188/88055705-1524ec00-cb68-11ea-9df5-a3863ceece20.png)

1. Time values are not correct (X axis)
2. Tooltip should display formatted value of time
**expected result:**
![image](https://user-images.githubusercontent.com/17744188/88055778-31c12400-cb68-11ea-9de4-e1b331296377.png)

**Comment by piorek** [comment]
fixed by #14 or #15
