### ISSUE TITLE
Spark UI doesn't work 

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx_widgets#27]
on groovy kernel:
![image](https://user-images.githubusercontent.com/17744188/89328105-8949ae80-d695-11ea-95f1-b39534ad9a3e.png)

**Comment by EfimovVladimir** [comment]
on python kernel:
![image](https://user-images.githubusercontent.com/17744188/89412994-aed7c600-d730-11ea-9303-33ebf1de3117.png)

**Comment by jaroslawmalekcodete** [comment]
jvm %%spark magic command fixes in :
https://github.com/twosigma/beakerx_kernel_scala/pull/9
https://github.com/twosigma/beakerx_kernel_base/pull/22
https://github.com/twosigma/beakerx_widgets/pull/37

**Comment by ildipo** [comment]
merged please verify
