### ISSUE TITLE
Legend not displayed

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx_widgets#36]
(Groovy kernel, Jupyter Notebook)
Current result:
![image](https://user-images.githubusercontent.com/17744188/91044507-0fff0500-e61e-11ea-8d1b-a84ba2b59def.png)

Expected result:
![image](https://user-images.githubusercontent.com/17744188/91044611-3cb31c80-e61e-11ea-9228-f43b73eb11b6.png)

**Comment by ildipo** [comment]
merged please verify
