### ISSUE TITLE
Info widget about added jars

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx_widgets#38]
(Groovy kernel, Jupyter Notebook, Ubuntu)
![image](https://user-images.githubusercontent.com/17744188/91297101-65661e00-e7a6-11ea-8a7b-edaf4d2c41aa.png)

expected result:
![image](https://user-images.githubusercontent.com/17744188/91297358-dd344880-e7a6-11ea-8971-c0cecfd104d1.png)

**Comment by jaroslawmalekcodete** [comment]
Hi @EfimovVladimir 
this problem was fixed [here](https://github.com/twosigma/beakerx_kernel_base/pull/22), please update master branch for beakerx_kernel_base and test it.

**Comment by ildipo** [comment]
merged please verify
