### ISSUE TITLE
(Plot) Display Name doesn't work

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx_widgets#4]
actual result:
![image](https://user-images.githubusercontent.com/17744188/87928021-d3734300-ca8c-11ea-9931-6181c2bf67c3.png)

expected result:
![image](https://user-images.githubusercontent.com/17744188/87928136-fd2c6a00-ca8c-11ea-8843-345fba313453.png)

**Comment by piorek** [comment]
this will be fixed by #14 or #15
