### ISSUE TITLE
(Plot) Milliseconds resolution doesn't work

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx_widgets#5]
Code to reproduce on python:
```
from beakerx_widgets.plots import *
import time

millis = 1507541201624;
hour = round(1000 * 60 * 60);
xs = [];
ys = [];
for i in range(11):
    xs.append(millis + hour * i);
    ys.append(i);

plot = TimePlot(timeZone="America/New_York")
plot.add(Points(x=xs, y=ys))
```

**Actual result:**
![image](https://user-images.githubusercontent.com/17744188/87930778-55656b00-ca91-11ea-8ae1-61d1712eccd7.png)

1. It displays current date value (2020 jul 20 ....) on X axis , not the date we defined. 
2. The date labels should be readable on X axis
3. The tooltip should display formatted date value

**Expected result:**
![image](https://user-images.githubusercontent.com/17744188/87931254-269bc480-ca92-11ea-9cde-2fa113216fa0.png)

**Comment by piorek** [comment]
fixed by #14 or #15
