### ISSUE TITLE
(Plot) Nanoseconds resolution doesn't work

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx_widgets#6]
Code to reproduce in python:
```
from beakerx_widgets.plots import *
import time

millis = 1507541201624;
nanos  = millis * 1000 * 1000
xs = []
ys = []
for i in range(11):
    xs.append(nanos + 7 * i)
    ys.append(i);

np = NanoPlot(timeZone="America/New_York")
np.add(Points(x=xs, y=ys))
```
**actual result:**
![image](https://user-images.githubusercontent.com/17744188/87932042-83e44580-ca93-11ea-964c-dc4025f79d7a.png)

1. It doesn't display correct date value on X axis (looks like it display current date value)
2. It doesn't display nanoseconds on X axis
3. Tooltip should display formatted date value

**expected result:**
![image](https://user-images.githubusercontent.com/17744188/87932213-cefe5880-ca93-11ea-85ee-9b7fcdd31925.png)

**Comment by piorek** [comment]
fixed by #14 or #15
